### ISSUE TITLE
Do we need Pekhui mod ? 

### ISSUE THREAD

**Issue by FudoStyle** [electron35/CobblemonPoketypedOrigins#2]
I feel like we need the mod Pehkui for the Bug type (smaller size) and the Dragon type (bigger size). 

But on the Poketyped Origins description on Modrinth:
https://modrinth.com/mod/poketyped-origins-for-cobblemon

There is no word  about Pehkui:
![image](https://github.com/user-attachments/assets/c086ec4e-34c9-4d3d-a4a6-5ed0e5a5c180)
![image](https://github.com/user-attachments/assets/0ebc427d-bc5c-4daf-98d1-171e09eccf2e)

This can create confusion for people who don't know how size modification works in Minecraft mods, and maybe they will not think to go download the Pehkui mod by themselves.

**Comment by electron35** [comment]
Fixed
